### ISSUE TITLE
Separate styling from symbols?

### ISSUE THREAD

**Issue by KyleKorndoerfer** [RicardoNiepel/Azure-PlantUML#4]
The Common file includes several declarations that modify the theme/skinparams for things like arrows. This has the result that if I include an Azure symbol in my Sequence diagram all of the arrows are changed and I have to override the skinparams in each of my diagrams to return them back to their default. Could you place the the skinparam modifications into a separate puml file (CommonStyles) so that those of us that would like to include _just the symbols_ can do so without changing the style(s) of our existing diagrams?

I can fork & submit a pull request if desired.

**Comment by RicardoNiepel** [comment]
Very good idea - I will do this

**Comment by RicardoNiepel** [comment]
Mh - I just thought about it and saw that this is already supported:
[Raw sprite usage](https://github.com/RicardoNiepel/Azure-PlantUML#raw-sprite-usage)

Do you mean/need anything else?

**Comment by RicardoNiepel** [comment]
Done with 21829dc99a390a4f7566f14e2d4e330cb9a8e67c

**Comment by KyleKorndoerfer** [comment]
Thank you! I look forward to it in the upstream PlantUML releases.
